# Generated by Django 5.2.1 on 2025-05-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
